spring.application.name=MediaLog

spring.datasource.url=jdbc:h2:mem:medialog
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
server.port=8081

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
